# Generated by Django 2.2.7 on 2019-11-27 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('god', '0002_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='checkOutTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
