# Generated by Django 2.2.7 on 2019-11-27 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('god', '0003_auto_20191127_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='inMeeting',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='checkInTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='client',
            name='checkOutTime',
            field=models.DateTimeField(),
        ),
    ]
