# Generated by Django 2.2.7 on 2019-11-27 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('god', '0004_auto_20191127_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='checkInTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='checkOutTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
