# Generated by Django 2.2.7 on 2019-11-28 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('god', '0005_auto_20191127_2255'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='Clients',
        ),
    ]
