# Generated by Django 2.2.7 on 2019-11-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('god', '0006_auto_20191128_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='inMeeting',
            field=models.BooleanField(default=True),
        ),
    ]
